server:
  port: 8082


spring:  datasource:    url:   jdbc:mysql://localhost:3306/ssm?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql1234
  jpa:
    #spring data jpa显示sql
    show-sql: true
  mvc:
    view:
      prefix: /templates/
      suffix: html
      




